### ISSUE TITLE
Create orders

### ISSUE THREAD

**Issue by stellakunzang** [stellakunzang/Crate#71]
Brainstorming the relationship here: 

A user has many subscriptions.
A crate has many subscriptions. 
Subscriptions belong to both users and crates.
If a user is to have many orders (which in turn of many products) I think the orders will also have to belong to both crate and user, and therefore be associated somehow with a subscription?

**Comment by Rostammahabadi** [comment]
The first three sound right and the relationships are built out in the app too. 
I'm wondering about creating a new table called orders or should we make a relationship between the crates and the products. 
Reasoning:
1. A user subscribes (subscription is created with a user and crateID) 
2. A crate is then added to the subscription
3. The crate has many products in it

Should we add the relationship between crate and products?

**Comment by Rostammahabadi** [comment]
It could look something like a crate has many products and products belong to a crate.

**Comment by stellakunzang** [comment]
@Rostammahabadi Yes, those relationships sound right because I was just putting into words what is already in the app 😅

I'm still a little fuzzy on what a crate is and it very well could be synonymous with the way I'm conceiving of order. I was wondering if a crate could be a type subscription which governs what is contained in an order but not the actual order itself. Maybe we can get some clarification tomorrow during our check-in?

**Comment by stellakunzang** [comment]
It looks like another option is to do something very similar to what we would do in Rails creating a joins table: 

`  Product.associate = function(models) {
    Product.belongsToMany(models.User, {through: models.UserProduct})
  }`

**Comment by Rostammahabadi** [comment]
What's still fuzzy for me is the part that says "and what I have kept" which indicates to me that returned could be a boolean field for the product (assuming they can return a single item from their crate)
