### ISSUE TITLE
Annotate: web/src/modules/user/Profile.js

### ISSUE THREAD

**Issue by Rostammahabadi** [stellakunzang/Crate#73]
Annotate for updating the shipping address and description for the user

**Comment by stellakunzang** [comment]
@Rostammahabadi I was thinking that everything in the `web/` directory was front end territory, but maybe I'm not putting adequate effort into decoding the javascript. Can you explain your thought process?

**Comment by Rostammahabadi** [comment]
We've been working on both front and backend for a while so was looking at everything instead of just BE lol, closing this issue
